// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://fptxuu7tzvck5oonzqvuuupx2q.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qcnh75mb6rbovkhm2l2anyqbji",
};

export default awsmobile;