// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://e5te3ubnrjgsfcgsxr6u5lrofe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yy62fo32unb6jaccenhoqvtb3i",
};

export default awsmobile;